name: Renderizar video con Manim

on:
  workflow_dispatch:
    # Toma de entrada el nombre del archivo a renderizar
    inputs:
      file:
        description: "Archivo a renderizar"
        default: "calculo"
        required: true
        type: string
      
      scene:
        description: "Escena a renderizar"
        default: "MainScene"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Carga el repositorio
      - uses: actions/checkout@v2

      # Configura python 3
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Actualizar lista de paquetes
      - name: Actualizar lista de paquetes
        run: sudo apt-get update

      # Instala archivos y dependencias necesarias
      - name: Instalar dependencias
        run: sudo apt install libcairo2-dev ffmpeg texlive-fonts-extra texlive-latex-recommended texlive texlive-latex-extra texlive-science tipa libpango1.0-dev

      # Actualizar pip e Instalar setuptools
      - name: Actualizar pip e Instalar setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
      # Instalar manim
      - name: Instalar manim
        run: pip install manim

      # Renderizar el archivo 
      - name: Renderizar archivo
        run: manim -ql animations/${{ github.event.inputs.file }}.py ${{ github.event.inputs.scene }}

      # Subir el archivo de video
      - name: Subir archivo de video
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: ./media/videos/${{ github.event.inputs.file }}/480p15/${{ github.event.inputs.scene }}.mp4