name: HQ manim render

on:
  workflow_dispatch:
    inputs:
      file:
        description: "Archivo a renderizar"
        default: "calculo"
        required: true
        type: string

      scene:
        description: "Escena a renderizar"
        default: "MainScene"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          # Carga el repositorio
          uses: actions/checkout@v2

          # Configura python 3
          uses: actions/setup-python@v2
          with:
            python-version: "3.x"

  setup:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          # Actualizar lista de paquetes
          sudo apt-get update

          # Instala archivos y dependencias necesarias
          sudo apt install libcairo2-dev ffmpeg texlive-fonts-extra texlive-latex-recommended texlive texlive-latex-extra texlive-science tipa libpango1.0-dev

  install:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: |
          # Actualizar pip e Instalar setuptools
          python -m pip install --upgrade pip
          pip install setuptools

          # Instalar manim
          pip install manim

  render:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Render
        run: |
          # Renderizar el archivo 
          manim -qh animations/${{ github.event.inputs.file }}.py ${{ github.event.inputs.scene }}

  upload:
    needs: render
    runs-on: ubuntu-latest

    steps:
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          # Subir el archivo de video
          name: video
          path: ./media/videos/${{ github.event.inputs.file }}/1080p60/${{ github.event.inputs.scene }}.mp4